language: nodejs
node_js:
  - 0.7
notifications:
  email: false
before_script:
  - node --version
  - sudo npm install -g grunt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - grunt  
